# Generated by Django 6.0.4 on 2026-05-05 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('requirements', models.TextField(blank=True, verbose_name='requirements')),
                ('skills_required', models.JSONField(blank=True, default=list, verbose_name='required skills')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('is_remote', models.BooleanField(default=False, verbose_name='remote work')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='minimum salary')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='maximum salary')),
                ('currency', models.CharField(default='KZT', max_length=3, verbose_name='currency')),
                ('duration', models.CharField(choices=[('1_week', 'Up to 1 week'), ('1_month', '1 week - 1 month'), ('1_3_months', '1-3 months'), ('3_6_months', '3-6 months'), ('6_12_months', '6-12 months'), ('1_year_plus', 'More than 1 year')], default='1_month', max_length=20, verbose_name='duration')),
                ('replacement_reason', models.CharField(choices=[('maternity', 'Maternity Leave'), ('sick', 'Sick Leave'), ('personal', 'Personal Leave'), ('training', 'Training/Internship'), ('other', 'Other')], default='other', max_length=20, verbose_name='replacement reason')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('manager_approved', models.BooleanField(default=False, verbose_name='manager approved')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='department')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='urgent')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vacancy',
                'verbose_name_plural': 'vacancies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='vacancies.vacancy')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'vacancy')},
            },
        ),
    ]
