# Generated by Django 6.0.4 on 2026-05-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='deleted_at',
        ),
    ]
