services:
  tempwork_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
      - esg-network

  tempwork_redis:
    image: redis:7-alpine
    networks:
      - app-network
      - esg-network

  tempwork_backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.backend
    env_file: backend/.env
    depends_on:
      - tempwork_db
      - tempwork_redis
    networks:
      - app-network
      - esg-network
    expose:
      - "8000"

  tempwork_frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile.frontend
    expose:
      - "80"
    depends_on:
      - tempwork_backend
    networks:
      - app-network
      - esg-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
  esg-network:
    external: true
